name: Build and deploy demo

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - run: cd example && yarn
      - run: cd example && yarn build
      - run: cd example && mkdir public && cd dist && cp *.* ../public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/public
          exclude_assets: ''
