name: Test and check codestyle

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, build, test
        run: |
          npm install
          npm run build
          npm test
        env:
          CI: true


  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install and check codestyle
        run: |
          npm install
          npm run codestyle
        env:
          CI: true
